"""
Document Generator — Produces polished Word (.docx) documents.

Uses python-docx to create professionally formatted documents with:
- Title page, headers, styled paragraphs
- Bullet lists and numbered items
- Tables with alternating row shading
- Consistent typography and spacing
"""

from __future__ import annotations

import os
import re
from datetime import datetime

from docx import Document
from docx.enum.table import WD_TABLE_ALIGNMENT
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.shared import Inches, Pt, RGBColor
from loguru import logger

from agent.models import ExecutionResult, Plan, ReflectionResult, SectionContent


class DocumentGenerator:
    """Generates a polished Word document from the execution result."""

    OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "output")

    def __init__(self) -> None:
        os.makedirs(self.OUTPUT_DIR, exist_ok=True)

    def generate(
        self,
        plan: Plan,
        result: ExecutionResult,
        reflection: ReflectionResult,
    ) -> str:
        """Create a .docx file and return the filename."""
        logger.info("📄 Document Generator: Building Word document...")

        doc = Document()
        self._set_default_styles(doc)
        self._add_title_page(doc, plan)
        self._add_metadata_section(doc, plan, reflection)

        # Add each content section
        for section in result.sections:
            self._add_section(doc, section)

        # Footer with generation info
        self._add_footer(doc, plan)

        # Save
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        safe_title = re.sub(r'[^\w\s-]', '', plan.document_title)
        safe_title = re.sub(r'\s+', '_', safe_title).strip('_')[:50]
        filename = f"{safe_title}_{timestamp}.docx"
        filepath = os.path.join(self.OUTPUT_DIR, filename)
        doc.save(filepath)

        logger.info(f"✅ Document saved: {filepath}")
        return filename

    def _set_default_styles(self, doc: Document) -> None:
        """Configure base document styles."""
        style = doc.styles["Normal"]
        font = style.font
        font.name = "Calibri"
        font.size = Pt(11)
        font.color.rgb = RGBColor(0x33, 0x33, 0x33)
        style.paragraph_format.space_after = Pt(6)
        style.paragraph_format.line_spacing = 1.15

        # Heading styles
        for level in range(1, 4):
            heading_style = doc.styles[f"Heading {level}"]
            heading_style.font.name = "Calibri"
            heading_style.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)
            if level == 1:
                heading_style.font.size = Pt(20)
                heading_style.font.bold = True
            elif level == 2:
                heading_style.font.size = Pt(15)
                heading_style.font.bold = True
            else:
                heading_style.font.size = Pt(12)
                heading_style.font.bold = True

    def _add_title_page(self, doc: Document, plan: Plan) -> None:
        """Add a professional title page."""
        # Spacing before title
        for _ in range(4):
            doc.add_paragraph("")

        # Document title
        title_para = doc.add_paragraph()
        title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title_para.add_run(plan.document_title)
        run.font.size = Pt(28)
        run.font.bold = True
        run.font.color.rgb = RGBColor(0x1A, 0x3C, 0x6E)

        # Document type subtitle
        subtitle = doc.add_paragraph()
        subtitle.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = subtitle.add_run(plan.document_type.value.replace("_", " ").title())
        run.font.size = Pt(14)
        run.font.color.rgb = RGBColor(0x66, 0x66, 0x66)
        run.font.italic = True

        # Horizontal rule
        doc.add_paragraph("─" * 50).alignment = WD_ALIGN_PARAGRAPH.CENTER

        # Date
        date_para = doc.add_paragraph()
        date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = date_para.add_run(f"Generated on {datetime.now().strftime('%B %d, %Y')}")
        run.font.size = Pt(11)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)

        # AI Attribution
        ai_para = doc.add_paragraph()
        ai_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = ai_para.add_run("Autonomously generated by AI Agent")
        run.font.size = Pt(10)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        run.font.italic = True

        doc.add_page_break()

    def _add_metadata_section(
        self, doc: Document, plan: Plan, reflection: ReflectionResult
    ) -> None:
        """Add document metadata: summary, assumptions, quality score."""
        doc.add_heading("Document Overview", level=1)

        # Summary
        doc.add_heading("Summary", level=2)
        doc.add_paragraph(plan.summary)

        # Assumptions (if any)
        if plan.assumptions:
            doc.add_heading("Assumptions Made", level=2)
            for assumption in plan.assumptions:
                para = doc.add_paragraph(assumption, style="List Bullet")
                para.paragraph_format.left_indent = Inches(0.25)

        # Quality score
        doc.add_heading("Quality Assessment", level=2)
        score_text = (
            f"This document received a quality score of {reflection.overall_score}/10 "
            f"from the autonomous review agent."
        )
        doc.add_paragraph(score_text)

        if reflection.improvement_suggestions:
            doc.add_paragraph("Review notes:")
            for suggestion in reflection.improvement_suggestions[:3]:
                doc.add_paragraph(suggestion, style="List Bullet")

        doc.add_paragraph("")  # spacer

    def _add_section(self, doc: Document, section: SectionContent) -> None:
        """Add a content section with heading, body, bullets, and optional table."""
        doc.add_heading(section.heading, level=1)

        # Body paragraphs
        if section.body:
            paragraphs = section.body.split("\n")
            for para_text in paragraphs:
                stripped = para_text.strip()
                if stripped:
                    doc.add_paragraph(stripped)

        # Bullet points
        if section.bullet_points:
            for bullet in section.bullet_points:
                para = doc.add_paragraph(bullet, style="List Bullet")
                para.paragraph_format.left_indent = Inches(0.25)

        # Table
        if section.table_data and len(section.table_data) > 0:
            self._add_table(doc, section.table_data)

        doc.add_paragraph("")  # spacer

    def _add_table(self, doc: Document, table_data: list[dict]) -> None:
        """Add a formatted table from a list of row dictionaries."""
        if not table_data:
            return

        headers = list(table_data[0].keys())
        table = doc.add_table(rows=1, cols=len(headers))
        table.alignment = WD_TABLE_ALIGNMENT.CENTER
        table.style = "Light Grid Accent 1"

        # Header row
        header_row = table.rows[0]
        for i, header in enumerate(headers):
            cell = header_row.cells[i]
            cell.text = header.replace("_", " ").title()
            # Bold header text
            for paragraph in cell.paragraphs:
                for run in paragraph.runs:
                    run.font.bold = True
                    run.font.size = Pt(10)

        # Data rows
        for row_data in table_data:
            row = table.add_row()
            for i, header in enumerate(headers):
                cell = row.cells[i]
                cell.text = str(row_data.get(header, ""))
                for paragraph in cell.paragraphs:
                    for run in paragraph.runs:
                        run.font.size = Pt(10)

    def _add_footer(self, doc: Document, plan: Plan) -> None:
        """Add a footer section with generation metadata."""
        doc.add_paragraph("")
        doc.add_paragraph("─" * 70)

        footer_para = doc.add_paragraph()
        footer_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = footer_para.add_run(
            f"This {plan.document_type.value.replace('_', ' ')} was autonomously "
            f"generated by an AI Agent on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}.\n"
            f"Document type: {plan.document_type.value} | "
            f"Sections: {len(plan.tasks)} | "
            f"Powered by Google Gemini"
        )
        run.font.size = Pt(8)
        run.font.color.rgb = RGBColor(0x99, 0x99, 0x99)
        run.font.italic = True
